[package]
name = "recall-stones"
version = "0.1.0"
authors = ["Shaik Azhar Madar <azarmadr@pm.me>"]
edition = "2021"

[features]
default = []
debug = ["menu-plugin/debug","memory/debug", "bevy-inspector-egui"]


[dependencies]
# bevy = { git = "https://github.com/bevyengine/bevy", rev = "b697e73c3d861c209152ccfb140ae00fbc6e9925", features = ["dynamic"] }
enum_dispatch = "0.3"
autodefault = "2.0.0"
memory = { path = "memory"}
menu-plugin = {path = "menu-plugin"}

# Hierarchy inspector debug
[dependencies.bevy-inspector-egui]
version = "0.10"
optional = true

[dependencies.bevy]
version = "0.7"
default-features = false
features = [
  "bevy_render",        # Rendering framework core
  "bevy_core_pipeline", # Higher-level rendering abstractions
  "bevy_text",          # Text/font rendering
  "bevy_ui",            # UI toolkit
  "bevy_winit",
  "png",
]

# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.7"
default-features = false
features = ["x11"]

[workspace]
members = [
  "memory",
  "menu-plugin",
  #"paper-plugin/mat"
]

# Enable optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Maybe also enable only a small amount of optimization for our code:
[profile.dev]
opt-level = 1

[profile.release]
strip = "debuginfo"
lto = "thin"

[package.metadata.android]
apk_label = "Recall Stones"
assets = "assets"
res = "assets/android-res"
icon = "@mipmap/ic_launcher"
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
min_sdk_version = 16
target_sdk_version = 29
