name: deploy-github-page

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-wasm-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown
      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'
      - name: Build Release
        run: |
          trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
      - name: optimize Wasm
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: dist/*.wasm
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: recall-stones
          ITCH_USER: azarmadr
          PACKAGE: dist
