name: Rust

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    strategy:
      matrix:
        toolchain: [nightly]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-wasm-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - run: |
          mkdir public -p
          cp index.html public
          cp -r assets public
          wasm-bindgen --out-dir public --target web target/wasm32-unknown-unknown/release/recall-stones.wasm
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: recall-stones
          ITCH_USER: azarmadr
          PACKAGE: public

  build-droid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-android-${{ hashFiles('**/Cargo.toml') }}
      - name: Uninstall android-31
        run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-31"
      - name: Install Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi
      - name: Install Cargo APK
        run: cargo install --force cargo-apk
      - name: Build APK
        run: cargo apk build --example android
      - run: tree target -I '.fingerprint|build|deps|examples|incremental'
        if: failure()
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: target
      - uses: actions/upload-artifact@v3
        with:
          path: target/release/apk
