name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    strategy:
      matrix:
        toolchain: [nightly]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-wasm-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - run: |
          mkdir public -p
          cp index.html public
          cp -r assets public
          wasm-bindgen --out-dir public --target web target/wasm32-unknown-unknown/release/recall-stones.wasm
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "fresh and empty gh-pages branch"
          git push origin gh-pages
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: recall-stones
          ITCH_USER: azarmadr
          PACKAGE: public
